# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 360c78ffd39e55f469d4cad216262cd195c1b4917263e2440047372eef9e19c627b90f35891d192c564de68f305e65839a53622a45012ec7560631d9824dec27

test:
  secret_key_base: f505e29d89494455f29e364be2734adfa8ad756f9abccd3c0cd5a017923682c1e331730664bc11fdef2db929c65f6b04175d5b12094cb288b50d870a9f5e562b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
